### PR TITLE
added new templates for Cloud Adoption Plan series

### PR DESCRIPTION
**Pull request by aksh-h**
[AB#3453](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3453)

### CODE REVIEW

**Comment by aksh-h** [comment]
@Damovisa and @dmckinstry add new templates for CAF series, request you to review the PR.

**Comment by dmckinstry** [comment]
As always... New template looks valid but I defer to the CAF team testing for final approval.

**Review by dmckinstry — APPROVED** [review]

**Comment by aksh-h** [comment]
Yes, all templates have been tested in staging and beta slot. As per the email exchange, author want to see the templates in live asap 🚀. If any changes required, updated template will be shared later.

**Review by Damovisa — APPROVED** [review]
Looks good to me.
I've seen CAF has looked at this and is happy so let's promote.

**Pull request merged**
